### ISSUE TITLE
Some are incompatible

### ISSUE THREAD

**Issue by baka4n** [CleanroomMC/Cleanroom#19] opened 2023-12-22 05:05 UTC
Some java8 features need to be replaced with java21 methods using special methods, such as java8's sun.reflect.Reflection

```text
java.lang.NoClassDefFoundError: sun/reflect/Reflection
	at quaternary.botaniatweaks.modules.shared.lib.GeneratingFlowers$FlowerData.<clinit>(GeneratingFlowers.java:101) ~[GeneratingFlowers$FlowerData.class:?]
	at quaternary.botaniatweaks.modules.shared.lib.GeneratingFlowers.<clinit>(GeneratingFlowers.java:30) ~[GeneratingFlowers.class:?]
	at quaternary.botaniatweaks.asm.tweaks.EverythingCanDecayTweak.computeAffectedClasses(EverythingCanDecayTweak.java:14) ~[EverythingCanDecayTweak.class:?]
	at quaternary.botaniatweaks.asm.tweaks.Tweak.getAffectedClasses(Tweak.java:18) ~[Tweak.class:?]
	at quaternary.botaniatweaks.asm.BotaniaTweakerTransformer.<clinit>(BotaniaTweakerTransformer.java:36) ~[BotaniaTweakerTransformer.class:?]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200) ~[?:?]
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243) ~[ASMTransformerWrapper$TransformerWrapper.class:?]
	at $wrapper.quaternary.botaniatweaks.asm.BotaniaTweakerTransformer.<init>(Unknown Source) ~[BotaniaTweakerTransformer.class:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
	at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:90) ~[bouncepad-0.4.13-cursed.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:134) ~[cleanroom-15.24.0.3020.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:145) [bouncepad-0.4.13-cursed.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:42) [bouncepad-0.4.13-cursed.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [cleanroom-15.24.0.3020.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [cleanroom-15.24.0.3020.jar:?]
Caused by: java.lang.ClassNotFoundException: sun.reflect.Reflection
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:108) ~[bouncepad-0.4.13-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 30 more

```

**Comment by Rongmario** [comment] 2023-12-22 05:08
Duplicate of #17, thank you anyway!

**Closed by Rongmario** 2023-12-22 05:08 UTC
