### ISSUE TITLE
Crash with Xaero's Minimap

### ISSUE THREAD

**Issue by MPCQUQ666** [CleanroomMC/Cleanroom#38] opened 2024-01-12 12:57 UTC
[crash-2024-01-12_20.51.34-client.txt](https://github.com/CleanroomMC/Cleanroom/files/13919319/crash-2024-01-12_20.51.34-client.txt)

**Comment by kappa-maintainer** [comment] 2024-01-13 13:02
How to reproduce the crash? I found the cause of this, but still need to test if the fix works

**Comment by MPCQUQ666** [comment] 2024-01-13 13:05
Can you speak Chinese?

**Comment by kappa-maintainer** [comment] 2024-01-13 13:06
Please contact with Chinese in Discord server
https://discord.gg/f2K4aSpG4F

**Comment by kappa-maintainer** [comment] 2024-01-14 01:35
Fixed in Fugue 0.3.4

**Closed by kappa-maintainer** 2024-01-14 01:35 UTC
