### ISSUE TITLE
Modded client with cleanroom crashes without audio

### ISSUE THREAD

**Issue by ipl-adm** [CleanroomMC/Cleanroom#224] opened 2024-10-16 20:04 UTC
### Your CleanroomMC Discord Username

b0rgir_

### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://pastes.dev/2Ud7nlKvau

### Mod List

In full log: https://pastes.dev/2Ud7nlKvau

### MMC Instance Notes

dont have (other launcher)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment] 2024-10-17 07:03
Caused by Voice Chat Mod, I guess

**Comment by Ecdcaeb** [comment] 2024-10-18 11:17
I could reproduce it without mod https://mclo.gs/kQaPCMJ

enter the game, click the `Single Player` buttom

**Comment by Rongmario** [comment] 2024-11-03 23:44
This is fixed in the recent builds.

**Closed by Rongmario** 2024-11-03 23:44 UTC
