### ISSUE TITLE
ProjectE's Dark Matter axe causes a crash when the skill cuts a tree.

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#72] opened 2024-02-24 12:52 UTC
Title, this did not happen in the exact same environment at FORGE, so perhaps the clean room is the cause.
It also occurred in cleanroom + cleanroom mods (Fugue, Vintagium, LoliASM, VintageFix) only.
This leads me to believe that the Dark Matter Axe skill is buggy.

**Comment by Rongmario** [comment] 2024-02-24 12:53
Crash report + log file please?

**Comment by erialsan** [comment] 2024-02-24 12:53
Create and prepare a minimum reproducible configuration.

**Comment by kappa-maintainer** [comment] 2024-03-17 10:11
Can't reproduce, please provide crash report and latest.log

**Comment by erialsan** [comment] 2024-03-17 13:57
I forgot to verify it while I was busy.
I'll do it now.

**Comment by erialsan** [comment] 2024-03-17 14:50
Skills other than axe can be activated.
Only evaporation of trees by axe does not work.

**Comment by erialsan** [comment] 2024-03-17 14:54
In the meantime, I will send you a Log. I may be able to find out something.

**Comment by erialsan** [comment] 2024-03-17 14:54
https://mclo.gs/WRAM45e

**Comment by Ecdcaeb** [comment] 2024-03-21 15:11
might some block do not have their own Item. So, ItemStack is empty.

**Comment by Rongmario** [comment] 2024-05-17 23:32
Closing as it's confirmed to be ProjectE's bug.

**Closed by Rongmario** 2024-05-17 23:32 UTC
