### ISSUE TITLE
Incompatibility List

### ISSUE THREAD

**Issue by mczph** [CleanroomMC/Cleanroom#23] opened 2023-12-30 12:41 UTC
Tested in a 500 mods modpack.

~~1.Mystical Lib
https://legacy.curseforge.com/minecraft/mc-mods/mysticallib 
https://mclo.gs/jqZphP2~~
~~3.Botanic Additions
https://www.curseforge.com/minecraft/mc-mods/botanic-additions
https://mclo.gs/y5YGdUl~~
4.Snow Real Magic
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic
https://mclo.gs/rbCEetV
[Already reported to mod author ](https://github.com/Snownee/SnowRealMagic/issues/344)
6.Entity Distance
https://www.curseforge.com/minecraft/mc-mods/entity-distance-1-12-2 
https://mclo.gs/Vp4Ah5a
7.Sledge Hammer
(This mod does have too many modifications that I don't expect to be compatible)

**Comment by kappa-maintainer** [comment] 2024-01-05 07:46
No.1 is a classic Field.set() error and is fixed
No.2 looks like a bug from the mod, please make sure you are at latest version and provide minimal crash mod combination
No.3 is fixed in Fugue
No.4 should be fixed in mod side and have been reported
I can reproduce No.5-7, please provide minimal crash combination and triggering instruction

**Comment by mczph** [comment] 2024-01-06 11:48
> No.1 is a classic Field.set() error and is fixed
> No.2 looks like a bug from the mod, please make sure you are at latest version and provide minimal crash mod combination
> No.3 is fixed in Fugue
> No.4 should be fixed in mod side and have been reported
> I can reproduce No.5-7, please provide minimal crash combination and triggering instruction

2 and 5 have been confirmed to be no problem. Regarding 6, it needs to be triggered when loading world.

**Closed** 2024-01-10 01:25 UTC
